### ISSUE TITLE
 Suggestion: Dark mode 

### ISSUE THREAD

**Issue by NissanOhana** [michael-maltsev/cheese-fork#20]
You're great! :)
Dark mode feature would be great

**Comment by Ali-Harbaji** [comment]
Would love to see Dark Mode too :)

**Comment by m417z** [comment]
Done!
https://www.facebook.com/cheesefork.technion/posts/pfbid02L9fJZNJzPHG1rxQxRLVGwKrh2r758Bx7u8Ku2yBbHwa62eSHzNt6Axcz4Xwc2KuAl

**Comment by michael-maltsev** [comment]
Done!
https://www.facebook.com/cheesefork.technion/posts/pfbid02L9fJZNJzPHG1rxQxRLVGwKrh2r758Bx7u8Ku2yBbHwa62eSHzNt6Axcz4Xwc2KuAl
