### ISSUE TITLE
changes in schedule are not reflected in .ics file

### ISSUE THREAD

**Issue by vladkeel** [michael-maltsev/cheese-fork#24]
to reproduce:
* create new schedule for semester.
* export as calendar to .ics file
* import the calendar from URL to Google Calendar.
* make changes to the schedule in cheese-fork

The changes are not reflected in Google Calendar. exporting as calendar again, removing calendar from Google Calendar and adding it from URL again does not help.

**Comment by michael-maltsev** [comment]
Google Calendar updates data from URL-imported calendars once every 12-24 hours or so. Once something changed in CheeseFork, after clicking on the export button, the changes will propagate to Google Calendar, but it will take a while. No need to remove and re-add the URL to Google Calendar.
