### ISSUE TITLE
Outlook errors when importing/syncing with Cheesefork (already found the fix)

### ISSUE THREAD

**Issue by NeatNit** [michael-maltsev/cheese-fork#25]
I've been getting these errors:

![image](https://user-images.githubusercontent.com/2400026/97846676-05847a00-1cf7-11eb-84ec-1f471156ea2e.png)

A bit of googling and the fix is evident - you must provide a timezone: https://stackoverflow.com/a/27102559/6778374

**Comment by michael-maltsev** [comment]
This stuff is tricky... I hope that it won't break other clients.
Before I implement the fix, please try it out and let me know whether it works.
Here are two files, one before the fix, the other after:
https://www.dropbox.com/sh/a2qaghob5bmxcx6/AADfTJXfBBH7jOuPN1_ZiPmIa?dl=1

Here's how it should look when imported, make sure the times are not off:
https://i.imgur.com/dUYW5MI.png

**Comment by NeatNit** [comment]
Sorry for the delay. The fix seems to work great with no errors!

**Comment by michael-maltsev** [comment]
Thanks, should be fixed now.
