### ISSUE TITLE
Suggestion: More links for subject groups.

### ISSUE THREAD

**Issue by Horef** [michael-maltsev/cheese-fork#26]
Hello, it would be very helpful if more links could be added to the subject descriptions (As in many cases because of the confines of WatsApp, people create two or three groups for big subjects, and you cannot store so much in CheeseFork as for now). Also in some cases WatsApp and Telegram groups exist so for such cases more fields for links would be of a great help.

**Comment by michael-maltsev** [comment]
Done: https://www.facebook.com/cheesefork.technion/posts/1311737179289593

![image](https://user-images.githubusercontent.com/36999014/148346241-3920738d-8ba4-45fd-8c39-df092c1b9fa1.png)
