### ISSUE TITLE
Add donate/sponsor button

### ISSUE THREAD

**Issue by gur111** [michael-maltsev/cheese-fork#30]
Either Sponsor button to Github or Donate in Cheesefork.
I made a small tool for about 300 people to use and one person donated.
Considering you have a few thousand users, I suspect many graduates (like me, tbh) would like to donate money to show their appreciation.
No one needs to pay but people would like to show appreciation.
A tiny PayBox link at the footer would be good enough.

**Comment by michael-maltsev** [comment]
Hi Gur, thank you for the suggestion and the support. I've added a donation option here in GitHub. You can use the "Sponsor" button at the top of this page.
