### ISSUE TITLE
Extract Zoom Lectures From הערות

### ISSUE THREAD

**Issue by PNone** [michael-maltsev/cheese-fork#34]
In the upcoming semester (202301), course 044102 has 2 lecture dates in its הערות, in the following format:
```
====================\\nחלק 2 (לבחירה אחד משני המועדים):\\n22.02, יום חמישי, 14.30-16.30, בזום\\n04.03, יום שני, 18.30-20.30, בזום\\n====================
```

Is it possible to parse it and add it to the calendar?

https://github.com/michael-maltsev/cheese-fork/blob/e74df47972a8bd1e6ec8f3ef165f3fe5f28642bc/deploy/course-manager.js#L56

**Comment by PNone** [comment]
@michael-maltsev Is it possible to add this edge case to the parser's logic?

**Comment by michael-maltsev** [comment]
As I said in https://github.com/michael-maltsev/technion-ug-info-fetcher/issues/2:

> The best solution for that is to contact the course staff and ask them to improve the way the information is presented on the students portal page.

But now as I look at it, the comments say the following:

> חלק 2 (לבחירה אחד משני המועדים):
> 22.02, יום חמישי, 14.30-16.30, בזום
> 04.03, יום שני, 18.30-20.30, בזום

As I understand it, it's either 22.02 or 04.03, i.e. one meeting only, not a weekly meeting. Therefore, it wouldn't be correct to add it to a calendar, which presents weekly events.

I'm closing the issue. If you think I'm missing something here, feel free to follow-up with a comment.

**Comment by PNone** [comment]
@michael-maltsev I would suggest to have a one time event in the calendar for these two zoom lectures if possible, similar to the events created for tests (except those ones can have hours as well).

Is it possible?

**Comment by michael-maltsev** [comment]
Tests can also have hours:

![image](https://github.com/michael-maltsev/cheese-fork/assets/36999014/5e964ca1-a61a-4f7f-aa5a-5d3a11936e77)

It's possible, but I don't believe that implementing this special case (and figuring out how to allow selecting between the two days) is worth it for this single course. Also I'm not sure that all users will want to see it in the corner near the exams.

**Comment by PNone** [comment]
> Tests can also have hours:
> 
> ![image](https://github.com/michael-maltsev/cheese-fork/assets/36999014/5e964ca1-a61a-4f7f-aa5a-5d3a11936e77)
> 
> It's possible, but I don't believe that implementing this special case (and figuring out how to allow selecting between the two days) is worth it for this single course. Also I'm not sure that all users will want to see it in the corner near the exams.

@michael-maltsev Ok. I was thinking about the calender export file as opposed to the tests section. But it indeed may not be worth it for this course on its own
