### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by doronbehar** [michael-maltsev/cheese-fork#36]
Hello,

Since last night I noticed that the service is 404:

https://cheesefork.cf/

Same with `files.cheesefork.cf`...

**Comment by michael-maltsev** [comment]
It's a global issue with .cf domains. I also wrote about it [here](https://www.facebook.com/cheesefork.technion/posts/pfbid0jZfuVyh5C969VTrDvHz1pK89BxApKXNTLtW8HcrrH4zkGbVuLAkSz7shZRSuV8jDl). For now, you can use the following backup address:
https://cheesefork.netlify.app/
