### ISSUE TITLE
Cache for 104032 out of date

### ISSUE THREAD

**Issue by PNone** [michael-maltsev/cheese-fork#38]
@michael-maltsev Course number 104032 has outdated data.
May you please refresh the cache file so the site shows latest schedule?

**Comment by michael-maltsev** [comment]
The cache is updated automatically every four hours or so. If it's still out-of-date after several hours, let me know and provide a difference for example so it'll be easier for me to check.

**Comment by PNone** [comment]
@michael-maltsev The cache is outdated for several weeks.
For example, Rivka's Tirgul at Sunday between 12:30-14:30 appears in students but not cheeskefork.
Fixed it locally by deleting the xml file

**Comment by michael-maltsev** [comment]
Here it is, unless you mean something else.
And what xml are you referring to?

![image](https://github.com/michael-maltsev/cheese-fork/assets/4129781/3285e068-8980-4dce-9ada-1d2907dba325)

**Comment by Urook** [comment]
> Here it is, unless you mean something else.
> And what xml are you referring to?
> 
> ![image](https://github.com/michael-maltsev/cheese-fork/assets/4129781/3285e068-8980-4dce-9ada-1d2907dba325)
> 

Excellent, I see it too now :)

**Comment by michael-maltsev** [comment]
Great. Just for the record, I didn't change anything.

**Comment by Urook** [comment]
> Great. Just for the record, I didn't change anything.

@michael-maltsev Huh. Maybe I should note the first time I got the good data was after I opened it in a new tab instead of refreshing. Maybe a browser cache thing?
