### ISSUE TITLE
Color issues with course icons in the sidebar

### ISSUE THREAD

**Issue by NatanBagrov** [michael-maltsev/cheese-fork#6]
Hey Michael,
Great tool :)
Please take a look at the image below:
![xnip2019-02-08_11-19-28](https://user-images.githubusercontent.com/20153650/52469233-97e40200-2b93-11e9-8b72-ed5cb28c9de3.jpg)
As can be seen, no color overlay on the "boxes".
MacOS Mojave 10.14.2, Chrome 71.0.3578.98 (which needs to be updated :( )

**Comment by michael-maltsev** [comment]
Hi Natan! :)
Looks like a Mac-specific issue. Should be fixed now.
