### ISSUE TITLE
feature for "im going only for lecture/tutorial"

### ISSUE THREAD

**Issue by avishayAv** [michael-maltsev/cheese-fork#7]
for instance, if in a certain course i've decided to go only to lectures, i think its a good idea to disable the tutorial hours in the scheduling screen. it will make it much more clean and easy to use

**Comment by michael-maltsev** [comment]
Maybe it can be done with a "clean version" checkbox which hides the lessons which aren't chosen. If so, I need to find a place for this checkbox :)

Another solution is to hide the lessons which aren't chosen from the shared schedule. I'm not sure that they are useful when sharing anyway.

You're using the system more than I am, so let me know what you think, and if you have other suggestions for implementing it UI-wise. I prefer to keep the UI as minimalistic as possible.

**Comment by michael-maltsev** [comment]
Done: https://www.facebook.com/cheesefork.technion/posts/1317779328685378

![image](https://user-images.githubusercontent.com/36999014/149652284-b3ecf1df-c48a-4879-a1f0-ef884b328c7b.png)
