### ISSUE TITLE
feature for printing version

### ISSUE THREAD

**Issue by avishayAv** [michael-maltsev/cheese-fork#8]
a webpage with good looking table contains only what i have chose

**Comment by michael-maltsev** [comment]
I'm using the [FullCalendar](https://fullcalendar.io/) library for displaying the calendar. I tried to improve the printing view, but looks like the library doesn't play well with printing. For now, I guess that the best option would be to make a screenshot and print the image.

If you have some experience in JS and want to experiment with it, pull requests are welcome :) I might as well look at it again one day.

**Comment by Tomerlm** [comment]
hey, you maybe can do a little workaround with library called html2canvas,
 if you would explain how I can run and test this on my machine, I can try and do the PR. (the idea is to take a snapshot of the main table and just send it to the printer, a bit hacky but can do the trick)

**Comment by michael-maltsev** [comment]
Hi @Tomerlm,

See my reply to the last quote here:
https://github.com/michael-maltsev/cheese-fork/issues/14#issuecomment-559012245

**Comment by michael-maltsev** [comment]
Done!
https://www.facebook.com/cheesefork.technion/posts/pfbid02FQLqwgGFoZuzTGXy2h8Dd2px9ShFpdCDLWgBUmXW5X8oY3fvwu6auqQx9dbphbtel
